<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BJ-AB055775-T" ignored="0" tests="2" failures="1" timestamp="2019-02-13T13:51:06 CST" time="4.059" errors="0">
  <testcase name="testFailed" time="2.019" classname="TimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TimeOutTest.testFailed() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TimeOutTest.testFailed() didn't finish within the time-out 2000
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(AbstractQueuedSynchronizer.java:1953)
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:716)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testFailed -->
  <testcase name="testSuccess" time="2.01" classname="TimeOutTest"/>
</testsuite>
